### PR TITLE
Move main code into trait

### PR DESCRIPTION
**Pull request by djmattyg007**
This allows SubStringy to be used as a mixin within a subclass of
Stringy which is combining multiple extensions.

### CODE REVIEW

**Comment by djmattyg007** [comment]
It looks like the tests are failing because `composer install` isn't being run before running the tests.

**Comment by TCB13** [comment]
@djmattyg007 can you provide an example on how you might combine two extensions if they are both following this trait logic? Should the final user create his own Stringy "abstraction" class that will use multiple traits such as this one?

**Comment by djmattyg007** [comment]
Yes, that's precisely the idea:

    namespace Vendor\Package;

    use Stringy\Stringy;
    use SubStringy\SubStringyTrait;
    use SliceableStringy\SliceableStringyTrait;

    class MyStringy extends Stringy
    {
        use SubStringyTrait;
        use SliceableStringyTrait;
    }

**Comment by TCB13** [comment]
@djmattyg007 and you are keeping the `class` as a backwards compatibility measure?

**Comment by djmattyg007** [comment]
Yes, there's no real reason to get rid of it that I can see.

**Comment by TCB13** [comment]
@djmattyg007 looks good! I'll merge this. close #1 .

**Pull request merged**
